@startuml

title Composite State Model
state "Game in Progress" as GameInProgress {
  state Player1 : Broadcast
  state Player2 : Broadcast
}

state "Connecting" as Connecting {
  WaitForPlayer1 --> WaitForPlayer2 : "Player 1 Connects"
  WaitForPlayer2 --> Player1 : "Player 2 Connects"
}

Player1 --> Player2: "Player 1\nPlays"
Player2 --> Player1: "Player 2\nPlays"



[*] -->  WaitForPlayer1 : "Application started"
GameInProgress --> GameOver : "Win or Draw"
@enduml

